### ISSUE TITLE
ligthness error 

### ISSUE THREAD

**Issue by e-struct** [bradtraversy/bizlight_theme#2]
@39 got a sass compile error with lightness  

/home/.../bizlight_theme/sass/app.scss
19:49:55
Error: Undefined operation: "ligthness(#f4f4f4) gt 50".
        on line 3 of /home/.../bizlight_theme/sass/_functions.scss
        from line 6 of /home/.../bizlight_theme/sass/app.scss
  Use --trace for backtrace.

I tried to used 'red' as color as a test but the same issue arised.
Error: Undefined operation: "ligthness(red) gt 50".

I lloked to the documentation but nothing helps so far 
**http://sass-lang.com/documentation/Sass/Script/Functions.html#lightness-instance_method**

Any help is welcome... 

Sass 3.4.21 (Selective Steve)
LSB Version:	core-9.20160110ubuntu0.2-ia32:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-ia32:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by e-struct** [comment]
Hum simple typo error. ligthness Vs lightness. So silly.

**Comment by JuanmeGarcia** [comment]
i got the same mistake on 2022 xd
